[package]
name = "cronoisseur"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
atty = "0.2"
clap = { version = "4.5", features = ["derive"] }
owo-colors = "4.0"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shlex = "1.3"
once_cell = "1.19"
